AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Resources:
  OrganizationUserCreate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: organizations/user/
      Handler: create.app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CompanyCreateUserPostAPI:
          Type: Api
          Properties:
            Path: '/user'
            Method: POST
            Auth:
              Authorizer: NONE

  OrganizationUserRead:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: organizations/user/
      Handler: read.app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CompanyUserGetAPI:
          Type: Api
          Properties:
            Path: '/user'
            Method: GET
            Auth:
              Authorizer: NONE

  OrganizationUserReadById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: organizations/user/
      Handler: read.app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CompanyUserGetByIdAPI:
          Type: Api
          Properties:
            Path: '/user/{Id}'
            Method: GET
            Auth:
              Authorizer: NONE

  OrganizationUserUpdateById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: organizations/user/
      Handler: update.app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CompanyUserUpdateByIdAPI:
          Type: Api
          Properties:
            Path: '/user/{Id}'
            Method: PUT
            Auth:
              Authorizer: NONE