AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Resources:
  OrganizationUserCreate:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: organizations/user/
      Handler: create.app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CompanyCreateUserPostAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: '/user'
            Method: POST
            Auth:
              Authorizer: NONE
